/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZodiacSignsRouteImport } from './routes/zodiac-signs'
import { Route as TreeRouteImport } from './routes/tree'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SephirothRouteImport } from './routes/sephiroth'
import { Route as ReadingsRouteImport } from './routes/readings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanetsRouteImport } from './routes/planets'
import { Route as PathsRouteImport } from './routes/paths'
import { Route as HebrewLettersRouteImport } from './routes/hebrew-letters'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AlchemicalPrinciplesRouteImport } from './routes/alchemical-principles'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ZodiacSignsSignIdRouteImport } from './routes/zodiac-signs.$signId'
import { Route as SephirothSephiraIdRouteImport } from './routes/sephiroth.$sephiraId'
import { Route as ReadingsNewRouteImport } from './routes/readings.new'
import { Route as ReadingsReadingIdRouteImport } from './routes/readings.$readingId'
import { Route as PlanetsPlanetIdRouteImport } from './routes/planets.$planetId'
import { Route as PathsPathIdRouteImport } from './routes/paths.$pathId'
import { Route as HebrewLettersLetterIdRouteImport } from './routes/hebrew-letters.$letterId'
import { Route as ElementsElementIdRouteImport } from './routes/elements.$elementId'
import { Route as CardsCardIdRouteImport } from './routes/cards.$cardId'
import { Route as AlchemicalPrinciplesPrincipleIdRouteImport } from './routes/alchemical-principles.$principleId'

const ZodiacSignsRoute = ZodiacSignsRouteImport.update({
  id: '/zodiac-signs',
  path: '/zodiac-signs',
  getParentRoute: () => rootRouteImport,
} as any)
const TreeRoute = TreeRouteImport.update({
  id: '/tree',
  path: '/tree',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SephirothRoute = SephirothRouteImport.update({
  id: '/sephiroth',
  path: '/sephiroth',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingsRoute = ReadingsRouteImport.update({
  id: '/readings',
  path: '/readings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanetsRoute = PlanetsRouteImport.update({
  id: '/planets',
  path: '/planets',
  getParentRoute: () => rootRouteImport,
} as any)
const PathsRoute = PathsRouteImport.update({
  id: '/paths',
  path: '/paths',
  getParentRoute: () => rootRouteImport,
} as any)
const HebrewLettersRoute = HebrewLettersRouteImport.update({
  id: '/hebrew-letters',
  path: '/hebrew-letters',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AlchemicalPrinciplesRoute = AlchemicalPrinciplesRouteImport.update({
  id: '/alchemical-principles',
  path: '/alchemical-principles',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ZodiacSignsSignIdRoute = ZodiacSignsSignIdRouteImport.update({
  id: '/$signId',
  path: '/$signId',
  getParentRoute: () => ZodiacSignsRoute,
} as any)
const SephirothSephiraIdRoute = SephirothSephiraIdRouteImport.update({
  id: '/$sephiraId',
  path: '/$sephiraId',
  getParentRoute: () => SephirothRoute,
} as any)
const ReadingsNewRoute = ReadingsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ReadingsRoute,
} as any)
const ReadingsReadingIdRoute = ReadingsReadingIdRouteImport.update({
  id: '/$readingId',
  path: '/$readingId',
  getParentRoute: () => ReadingsRoute,
} as any)
const PlanetsPlanetIdRoute = PlanetsPlanetIdRouteImport.update({
  id: '/$planetId',
  path: '/$planetId',
  getParentRoute: () => PlanetsRoute,
} as any)
const PathsPathIdRoute = PathsPathIdRouteImport.update({
  id: '/$pathId',
  path: '/$pathId',
  getParentRoute: () => PathsRoute,
} as any)
const HebrewLettersLetterIdRoute = HebrewLettersLetterIdRouteImport.update({
  id: '/$letterId',
  path: '/$letterId',
  getParentRoute: () => HebrewLettersRoute,
} as any)
const ElementsElementIdRoute = ElementsElementIdRouteImport.update({
  id: '/$elementId',
  path: '/$elementId',
  getParentRoute: () => ElementsRoute,
} as any)
const CardsCardIdRoute = CardsCardIdRouteImport.update({
  id: '/$cardId',
  path: '/$cardId',
  getParentRoute: () => CardsRoute,
} as any)
const AlchemicalPrinciplesPrincipleIdRoute =
  AlchemicalPrinciplesPrincipleIdRouteImport.update({
    id: '/$principleId',
    path: '/$principleId',
    getParentRoute: () => AlchemicalPrinciplesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alchemical-principles': typeof AlchemicalPrinciplesRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/elements': typeof ElementsRouteWithChildren
  '/hebrew-letters': typeof HebrewLettersRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/planets': typeof PlanetsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/sephiroth': typeof SephirothRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tree': typeof TreeRoute
  '/zodiac-signs': typeof ZodiacSignsRouteWithChildren
  '/alchemical-principles/$principleId': typeof AlchemicalPrinciplesPrincipleIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/elements/$elementId': typeof ElementsElementIdRoute
  '/hebrew-letters/$letterId': typeof HebrewLettersLetterIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/readings/$readingId': typeof ReadingsReadingIdRoute
  '/readings/new': typeof ReadingsNewRoute
  '/sephiroth/$sephiraId': typeof SephirothSephiraIdRoute
  '/zodiac-signs/$signId': typeof ZodiacSignsSignIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alchemical-principles': typeof AlchemicalPrinciplesRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/elements': typeof ElementsRouteWithChildren
  '/hebrew-letters': typeof HebrewLettersRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/planets': typeof PlanetsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/sephiroth': typeof SephirothRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tree': typeof TreeRoute
  '/zodiac-signs': typeof ZodiacSignsRouteWithChildren
  '/alchemical-principles/$principleId': typeof AlchemicalPrinciplesPrincipleIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/elements/$elementId': typeof ElementsElementIdRoute
  '/hebrew-letters/$letterId': typeof HebrewLettersLetterIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/readings/$readingId': typeof ReadingsReadingIdRoute
  '/readings/new': typeof ReadingsNewRoute
  '/sephiroth/$sephiraId': typeof SephirothSephiraIdRoute
  '/zodiac-signs/$signId': typeof ZodiacSignsSignIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alchemical-principles': typeof AlchemicalPrinciplesRouteWithChildren
  '/cards': typeof CardsRouteWithChildren
  '/elements': typeof ElementsRouteWithChildren
  '/hebrew-letters': typeof HebrewLettersRouteWithChildren
  '/paths': typeof PathsRouteWithChildren
  '/planets': typeof PlanetsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/readings': typeof ReadingsRouteWithChildren
  '/sephiroth': typeof SephirothRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/tree': typeof TreeRoute
  '/zodiac-signs': typeof ZodiacSignsRouteWithChildren
  '/alchemical-principles/$principleId': typeof AlchemicalPrinciplesPrincipleIdRoute
  '/cards/$cardId': typeof CardsCardIdRoute
  '/elements/$elementId': typeof ElementsElementIdRoute
  '/hebrew-letters/$letterId': typeof HebrewLettersLetterIdRoute
  '/paths/$pathId': typeof PathsPathIdRoute
  '/planets/$planetId': typeof PlanetsPlanetIdRoute
  '/readings/$readingId': typeof ReadingsReadingIdRoute
  '/readings/new': typeof ReadingsNewRoute
  '/sephiroth/$sephiraId': typeof SephirothSephiraIdRoute
  '/zodiac-signs/$signId': typeof ZodiacSignsSignIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alchemical-principles'
    | '/cards'
    | '/elements'
    | '/hebrew-letters'
    | '/paths'
    | '/planets'
    | '/profile'
    | '/readings'
    | '/sephiroth'
    | '/sign-in'
    | '/sign-up'
    | '/tree'
    | '/zodiac-signs'
    | '/alchemical-principles/$principleId'
    | '/cards/$cardId'
    | '/elements/$elementId'
    | '/hebrew-letters/$letterId'
    | '/paths/$pathId'
    | '/planets/$planetId'
    | '/readings/$readingId'
    | '/readings/new'
    | '/sephiroth/$sephiraId'
    | '/zodiac-signs/$signId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alchemical-principles'
    | '/cards'
    | '/elements'
    | '/hebrew-letters'
    | '/paths'
    | '/planets'
    | '/profile'
    | '/readings'
    | '/sephiroth'
    | '/sign-in'
    | '/sign-up'
    | '/tree'
    | '/zodiac-signs'
    | '/alchemical-principles/$principleId'
    | '/cards/$cardId'
    | '/elements/$elementId'
    | '/hebrew-letters/$letterId'
    | '/paths/$pathId'
    | '/planets/$planetId'
    | '/readings/$readingId'
    | '/readings/new'
    | '/sephiroth/$sephiraId'
    | '/zodiac-signs/$signId'
  id:
    | '__root__'
    | '/'
    | '/alchemical-principles'
    | '/cards'
    | '/elements'
    | '/hebrew-letters'
    | '/paths'
    | '/planets'
    | '/profile'
    | '/readings'
    | '/sephiroth'
    | '/sign-in'
    | '/sign-up'
    | '/tree'
    | '/zodiac-signs'
    | '/alchemical-principles/$principleId'
    | '/cards/$cardId'
    | '/elements/$elementId'
    | '/hebrew-letters/$letterId'
    | '/paths/$pathId'
    | '/planets/$planetId'
    | '/readings/$readingId'
    | '/readings/new'
    | '/sephiroth/$sephiraId'
    | '/zodiac-signs/$signId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlchemicalPrinciplesRoute: typeof AlchemicalPrinciplesRouteWithChildren
  CardsRoute: typeof CardsRouteWithChildren
  ElementsRoute: typeof ElementsRouteWithChildren
  HebrewLettersRoute: typeof HebrewLettersRouteWithChildren
  PathsRoute: typeof PathsRouteWithChildren
  PlanetsRoute: typeof PlanetsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ReadingsRoute: typeof ReadingsRouteWithChildren
  SephirothRoute: typeof SephirothRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TreeRoute: typeof TreeRoute
  ZodiacSignsRoute: typeof ZodiacSignsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zodiac-signs': {
      id: '/zodiac-signs'
      path: '/zodiac-signs'
      fullPath: '/zodiac-signs'
      preLoaderRoute: typeof ZodiacSignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tree': {
      id: '/tree'
      path: '/tree'
      fullPath: '/tree'
      preLoaderRoute: typeof TreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sephiroth': {
      id: '/sephiroth'
      path: '/sephiroth'
      fullPath: '/sephiroth'
      preLoaderRoute: typeof SephirothRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/readings': {
      id: '/readings'
      path: '/readings'
      fullPath: '/readings'
      preLoaderRoute: typeof ReadingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planets': {
      id: '/planets'
      path: '/planets'
      fullPath: '/planets'
      preLoaderRoute: typeof PlanetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paths': {
      id: '/paths'
      path: '/paths'
      fullPath: '/paths'
      preLoaderRoute: typeof PathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hebrew-letters': {
      id: '/hebrew-letters'
      path: '/hebrew-letters'
      fullPath: '/hebrew-letters'
      preLoaderRoute: typeof HebrewLettersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alchemical-principles': {
      id: '/alchemical-principles'
      path: '/alchemical-principles'
      fullPath: '/alchemical-principles'
      preLoaderRoute: typeof AlchemicalPrinciplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zodiac-signs/$signId': {
      id: '/zodiac-signs/$signId'
      path: '/$signId'
      fullPath: '/zodiac-signs/$signId'
      preLoaderRoute: typeof ZodiacSignsSignIdRouteImport
      parentRoute: typeof ZodiacSignsRoute
    }
    '/sephiroth/$sephiraId': {
      id: '/sephiroth/$sephiraId'
      path: '/$sephiraId'
      fullPath: '/sephiroth/$sephiraId'
      preLoaderRoute: typeof SephirothSephiraIdRouteImport
      parentRoute: typeof SephirothRoute
    }
    '/readings/new': {
      id: '/readings/new'
      path: '/new'
      fullPath: '/readings/new'
      preLoaderRoute: typeof ReadingsNewRouteImport
      parentRoute: typeof ReadingsRoute
    }
    '/readings/$readingId': {
      id: '/readings/$readingId'
      path: '/$readingId'
      fullPath: '/readings/$readingId'
      preLoaderRoute: typeof ReadingsReadingIdRouteImport
      parentRoute: typeof ReadingsRoute
    }
    '/planets/$planetId': {
      id: '/planets/$planetId'
      path: '/$planetId'
      fullPath: '/planets/$planetId'
      preLoaderRoute: typeof PlanetsPlanetIdRouteImport
      parentRoute: typeof PlanetsRoute
    }
    '/paths/$pathId': {
      id: '/paths/$pathId'
      path: '/$pathId'
      fullPath: '/paths/$pathId'
      preLoaderRoute: typeof PathsPathIdRouteImport
      parentRoute: typeof PathsRoute
    }
    '/hebrew-letters/$letterId': {
      id: '/hebrew-letters/$letterId'
      path: '/$letterId'
      fullPath: '/hebrew-letters/$letterId'
      preLoaderRoute: typeof HebrewLettersLetterIdRouteImport
      parentRoute: typeof HebrewLettersRoute
    }
    '/elements/$elementId': {
      id: '/elements/$elementId'
      path: '/$elementId'
      fullPath: '/elements/$elementId'
      preLoaderRoute: typeof ElementsElementIdRouteImport
      parentRoute: typeof ElementsRoute
    }
    '/cards/$cardId': {
      id: '/cards/$cardId'
      path: '/$cardId'
      fullPath: '/cards/$cardId'
      preLoaderRoute: typeof CardsCardIdRouteImport
      parentRoute: typeof CardsRoute
    }
    '/alchemical-principles/$principleId': {
      id: '/alchemical-principles/$principleId'
      path: '/$principleId'
      fullPath: '/alchemical-principles/$principleId'
      preLoaderRoute: typeof AlchemicalPrinciplesPrincipleIdRouteImport
      parentRoute: typeof AlchemicalPrinciplesRoute
    }
  }
}

interface AlchemicalPrinciplesRouteChildren {
  AlchemicalPrinciplesPrincipleIdRoute: typeof AlchemicalPrinciplesPrincipleIdRoute
}

const AlchemicalPrinciplesRouteChildren: AlchemicalPrinciplesRouteChildren = {
  AlchemicalPrinciplesPrincipleIdRoute: AlchemicalPrinciplesPrincipleIdRoute,
}

const AlchemicalPrinciplesRouteWithChildren =
  AlchemicalPrinciplesRoute._addFileChildren(AlchemicalPrinciplesRouteChildren)

interface CardsRouteChildren {
  CardsCardIdRoute: typeof CardsCardIdRoute
}

const CardsRouteChildren: CardsRouteChildren = {
  CardsCardIdRoute: CardsCardIdRoute,
}

const CardsRouteWithChildren = CardsRoute._addFileChildren(CardsRouteChildren)

interface ElementsRouteChildren {
  ElementsElementIdRoute: typeof ElementsElementIdRoute
}

const ElementsRouteChildren: ElementsRouteChildren = {
  ElementsElementIdRoute: ElementsElementIdRoute,
}

const ElementsRouteWithChildren = ElementsRoute._addFileChildren(
  ElementsRouteChildren,
)

interface HebrewLettersRouteChildren {
  HebrewLettersLetterIdRoute: typeof HebrewLettersLetterIdRoute
}

const HebrewLettersRouteChildren: HebrewLettersRouteChildren = {
  HebrewLettersLetterIdRoute: HebrewLettersLetterIdRoute,
}

const HebrewLettersRouteWithChildren = HebrewLettersRoute._addFileChildren(
  HebrewLettersRouteChildren,
)

interface PathsRouteChildren {
  PathsPathIdRoute: typeof PathsPathIdRoute
}

const PathsRouteChildren: PathsRouteChildren = {
  PathsPathIdRoute: PathsPathIdRoute,
}

const PathsRouteWithChildren = PathsRoute._addFileChildren(PathsRouteChildren)

interface PlanetsRouteChildren {
  PlanetsPlanetIdRoute: typeof PlanetsPlanetIdRoute
}

const PlanetsRouteChildren: PlanetsRouteChildren = {
  PlanetsPlanetIdRoute: PlanetsPlanetIdRoute,
}

const PlanetsRouteWithChildren =
  PlanetsRoute._addFileChildren(PlanetsRouteChildren)

interface ReadingsRouteChildren {
  ReadingsReadingIdRoute: typeof ReadingsReadingIdRoute
  ReadingsNewRoute: typeof ReadingsNewRoute
}

const ReadingsRouteChildren: ReadingsRouteChildren = {
  ReadingsReadingIdRoute: ReadingsReadingIdRoute,
  ReadingsNewRoute: ReadingsNewRoute,
}

const ReadingsRouteWithChildren = ReadingsRoute._addFileChildren(
  ReadingsRouteChildren,
)

interface SephirothRouteChildren {
  SephirothSephiraIdRoute: typeof SephirothSephiraIdRoute
}

const SephirothRouteChildren: SephirothRouteChildren = {
  SephirothSephiraIdRoute: SephirothSephiraIdRoute,
}

const SephirothRouteWithChildren = SephirothRoute._addFileChildren(
  SephirothRouteChildren,
)

interface ZodiacSignsRouteChildren {
  ZodiacSignsSignIdRoute: typeof ZodiacSignsSignIdRoute
}

const ZodiacSignsRouteChildren: ZodiacSignsRouteChildren = {
  ZodiacSignsSignIdRoute: ZodiacSignsSignIdRoute,
}

const ZodiacSignsRouteWithChildren = ZodiacSignsRoute._addFileChildren(
  ZodiacSignsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlchemicalPrinciplesRoute: AlchemicalPrinciplesRouteWithChildren,
  CardsRoute: CardsRouteWithChildren,
  ElementsRoute: ElementsRouteWithChildren,
  HebrewLettersRoute: HebrewLettersRouteWithChildren,
  PathsRoute: PathsRouteWithChildren,
  PlanetsRoute: PlanetsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ReadingsRoute: ReadingsRouteWithChildren,
  SephirothRoute: SephirothRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TreeRoute: TreeRoute,
  ZodiacSignsRoute: ZodiacSignsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
